a= int(input("enter the input ="))
print(a)
print ("The data type of input value is :" ,type(a))
b= str(input("enter the input ="))
print(b)
print ("The data type of input value is :" ,type(b))
c= float(input("enter the input ="))
print(c)
print ("The data type of input value is :" ,type(c))
d= bool(input("enter the input ="))
print(d)
print ("The data type of input value is :" ,type(d))